/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ExchangeInterface extends ethers.utils.Interface {
  functions: {
    "areOpenForTrades(uint256)": FunctionFragment;
    "buy(uint256)": FunctionFragment;
    "cancelSell(uint256)": FunctionFragment;
    "directBuyCo2FromToken(uint256)": FunctionFragment;
    "getAllNFTOpenForTrades()": FunctionFragment;
    "getUsedNFTs()": FunctionFragment;
    "nftOpenForTradeArray(uint256)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "openForTrades(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "sell(uint256,uint256)": FunctionFragment;
    "superNFT()": FunctionFragment;
    "superToken()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transformNFTToCo2Credit(uint256)": FunctionFragment;
    "usedNFTs(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "areOpenForTrades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "buy", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelSell",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "directBuyCo2FromToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllNFTOpenForTrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUsedNFTs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftOpenForTradeArray",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openForTrades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "superNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "superToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transformNFTToCo2Credit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNFTs",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "areOpenForTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelSell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "directBuyCo2FromToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllNFTOpenForTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUsedNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftOpenForTradeArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openForTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "superNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "superToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transformNFTToCo2Credit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedNFTs", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "UpdateUsedNFT(tuple[],uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateUsedNFT"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type UpdateUsedNFTEvent = TypedEvent<
  [
    ([string, BigNumber, string] & {
      customer: string;
      tokenId: BigNumber;
      tokenURI: string;
    })[],
    BigNumber[]
  ] & {
    _usedNFTs: ([string, BigNumber, string] & {
      customer: string;
      tokenId: BigNumber;
      tokenURI: string;
    })[];
    _nftOpenForTradeArray: BigNumber[];
  }
>;

export class Exchange extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ExchangeInterface;

  functions: {
    areOpenForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    buy(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelSell(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    directBuyCo2FromToken(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAllNFTOpenForTrades(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getUsedNFTs(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, string] & {
          customer: string;
          tokenId: BigNumber;
          tokenURI: string;
        })[]
      ]
    >;

    nftOpenForTradeArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string] & {
        seller: string;
        nftTokenId: BigNumber;
        price: BigNumber;
        status: string;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sell(
      _nftTokenId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    superNFT(overrides?: CallOverrides): Promise<[string]>;

    superToken(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transformNFTToCo2Credit(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    usedNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        customer: string;
        tokenId: BigNumber;
        tokenURI: string;
      }
    >;
  };

  areOpenForTrades(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  buy(
    _nftTokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelSell(
    _nftTokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  directBuyCo2FromToken(
    _nftTokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAllNFTOpenForTrades(overrides?: CallOverrides): Promise<BigNumber[]>;

  getUsedNFTs(
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, string] & {
      customer: string;
      tokenId: BigNumber;
      tokenURI: string;
    })[]
  >;

  nftOpenForTradeArray(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  onERC721Received(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openForTrades(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, string] & {
      seller: string;
      nftTokenId: BigNumber;
      price: BigNumber;
      status: string;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sell(
    _nftTokenId: BigNumberish,
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  superNFT(overrides?: CallOverrides): Promise<string>;

  superToken(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transformNFTToCo2Credit(
    _nftTokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  usedNFTs(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string] & {
      customer: string;
      tokenId: BigNumber;
      tokenURI: string;
    }
  >;

  callStatic: {
    areOpenForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    buy(_nftTokenId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    cancelSell(
      _nftTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    directBuyCo2FromToken(
      _nftTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllNFTOpenForTrades(overrides?: CallOverrides): Promise<BigNumber[]>;

    getUsedNFTs(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, string] & {
        customer: string;
        tokenId: BigNumber;
        tokenURI: string;
      })[]
    >;

    nftOpenForTradeArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    openForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string] & {
        seller: string;
        nftTokenId: BigNumber;
        price: BigNumber;
        status: string;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    sell(
      _nftTokenId: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    superNFT(overrides?: CallOverrides): Promise<string>;

    superToken(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transformNFTToCo2Credit(
      _nftTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    usedNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        customer: string;
        tokenId: BigNumber;
        tokenURI: string;
      }
    >;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "UpdateUsedNFT(tuple[],uint256[])"(
      _usedNFTs?: null,
      _nftOpenForTradeArray?: null
    ): TypedEventFilter<
      [
        ([string, BigNumber, string] & {
          customer: string;
          tokenId: BigNumber;
          tokenURI: string;
        })[],
        BigNumber[]
      ],
      {
        _usedNFTs: ([string, BigNumber, string] & {
          customer: string;
          tokenId: BigNumber;
          tokenURI: string;
        })[];
        _nftOpenForTradeArray: BigNumber[];
      }
    >;

    UpdateUsedNFT(
      _usedNFTs?: null,
      _nftOpenForTradeArray?: null
    ): TypedEventFilter<
      [
        ([string, BigNumber, string] & {
          customer: string;
          tokenId: BigNumber;
          tokenURI: string;
        })[],
        BigNumber[]
      ],
      {
        _usedNFTs: ([string, BigNumber, string] & {
          customer: string;
          tokenId: BigNumber;
          tokenURI: string;
        })[];
        _nftOpenForTradeArray: BigNumber[];
      }
    >;
  };

  estimateGas: {
    areOpenForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelSell(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    directBuyCo2FromToken(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAllNFTOpenForTrades(overrides?: CallOverrides): Promise<BigNumber>;

    getUsedNFTs(overrides?: CallOverrides): Promise<BigNumber>;

    nftOpenForTradeArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sell(
      _nftTokenId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    superNFT(overrides?: CallOverrides): Promise<BigNumber>;

    superToken(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transformNFTToCo2Credit(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    usedNFTs(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    areOpenForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buy(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelSell(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    directBuyCo2FromToken(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAllNFTOpenForTrades(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUsedNFTs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftOpenForTradeArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openForTrades(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sell(
      _nftTokenId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    superNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    superToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transformNFTToCo2Credit(
      _nftTokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    usedNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
